### ISSUE TITLE
Docker pull failure for Fischertechnik device

### ISSUE THREAD

**Issue by gcloughley** [edgexfoundry/developer-scripts#12]
Although commented-out, the typo "**device-fischetechnik**" instead of device-fischertechnik does lead to failure when the docker image is pulled:

$ docker-compose up
Pulling device-fischetechnik (edgexfoundry/docker-device-fischetechnik:latest)...
ERROR: repository edgexfoundry/docker-device-fischetechnik not found: does not exist or no pull access

Does this need to be fixed in Jenkins also?

  **# _device-fischetechnik_:
    # image: edgexfoundry/docker-device-_fischetechnik_
    # ports:
      # - "49985:49985"
    # container_name: edgex-device-_fischetechnik_
    # hostname: edgex-device-_fischetechnik_
    # networks:
      # - edgex-network
    # volumes_from:
      # - volume
    # privileged: true
    # depends_on:
      # - volume
      # - consul
      # - config-seed
      # - mongo
      # - logging
      # - metadata
      # - data
      # - command**

**Comment by trcox** [comment]
Thanks for the ID @gcloughley, this issue looks to be isolated to this file!
