### ISSUE TITLE
docker-compose-edinburgh-1.0.0.yml inconsistent/missing images

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/developer-scripts#120]
docker-compose-edinburgh-1.0.0.yml currently contains references to non-existent images (all edgexfoundry/\*:1.0.0).  device-virtual has a reference that is inconsistent with the others (nexus3.edgexfoundry.org:10004/\*:1.0.0).

**Comment by tsconn23** [comment]
Yes, those images won't be published until the actual release.
