### ISSUE TITLE
Inconsistent network aliases in docker-compose-edinburgh-1.0.0.yml

### ISSUE THREAD

**Issue by antoniomtz** [edgexfoundry/developer-scripts#130]
Hi,

When deploying edgex Edinburgh as a docker stack, _hostname_ and _container_name_ attributes are not supported, hence, the need of **network aliases** in every service is required. 
Only some of them have network alias defined. 

Adding consistency in network aliases in all services will ensure this docker-compose file works for docker stack and docker-compose. 

Thanks,
Antonio

**Comment by tsconn23** [comment]
@jpwhitemn FYI for dot release compose files

**Comment by jpwhitemn** [comment]
Yep - saw it.  On it.

    On Thursday, July 18, 2019, 5:44:06 PM CDT, Trevor Conn <notifications@github.com> wrote:  
 
 
@jpwhitemn FYI for dot release compose files
