### ISSUE TITLE
Set no-new-privileges option on containers

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/developer-scripts#143]
# 🚀 Feature Request

### Description
This is a scored item on the CIS Docker benchmarks.  Whenever possible, docker containers should be run with the "no-new-privileges" option.  This option prevents SUID/SGID binaries in the container from obtaining additional privileges.

The option should be universally enabled for all containers in the Dockerfile and issues raised for exceptions.

**Comment by hutchic** [comment]
pending edgexfoundry/edgex-docs#206 and should be compliant on the result

**Comment by lenny-intel** [comment]
Blocked waiting on new ADR (https://github.com/edgexfoundry/edgex-docs/issues/206)

**Comment by bnevis-i** [comment]
PR is merged. Unblocking.  For for consideration for Ireland.
