### ISSUE TITLE
Clean up docker-compose

### ISSUE THREAD

**Issue by rsdmike** [edgexfoundry/developer-scripts#163]
As I've combed through the docker-compose files in the nightly build, and previous releases, I've noticed a few unnecessary items. Namely, there is absolutely no need to map consul data, log data, and the database files into each service.  All services communicate to mongo via the mongo container which has its database properly mounted, however no other container has any use for this directory/volume.
This is the same for consul as only consul should have it's data persisted, no other service needs this. 
Log data is a little less clear, however, since enable remote logging should be enabled in all services, this negates the need to persist in locally in each container and no data is written to a local log if remote is enabled rending the mount useless. 

Further more I would be concerned that any service may potentially alter or modify files in those mounts that it shouldn't have access to. I.e. remove db files, or reading another services logs could be construed as a security concern. 

I think it would be a good idea to do this for Fuji. Possibly even update previous compose files as well

**Comment by beaufrusetta** [comment]
I approve of this issue. ;-)

**Comment by lenny-intel** [comment]
Along these line, the network aliasing that is in the Edinburgh compose files never made it into the these nightly build compose files, which are being used as staging for the Fuji compose files. As part of this clean-up the network aliasing should be added.

**Comment by michaelestrin** [comment]
Closing; open PR was merged.
