### ISSUE TITLE
Nightly build Redis version of compose file has issues with Device Virtual

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/developer-scripts#169]
Using the nightly build  docker-compose-nexus-redis-no-secty.yml the Device Virtual service get the following error:
```
level=ERROR ts=2019-10-25T23:17:59.2434737Z app=device-virtual source=init.go:30 msg="Value Descriptor cache initialization failed: 500 - ERR unknown command `RANGE`, with args beginning with: `valueDescriptor`, `0`, `-1`, \n"
```

**Comment by andresrinivasan** [comment]
@lenny-intel What change caused the breakage?

**Comment by lenny-intel** [comment]
@andresrinivasan, I have no clue. My guess is no one has actually tested it... I was testing my PR to add App Service Configurable and found that  docker-compose-nexus-redis-no-secty.yml doen't work.

**Comment by andresrinivasan** [comment]
Ah. Bummer. I'm going to need help as I can't get to this before the F2F. If you have everything set up, we can get on a screen share and look at exactly what is happening.

**Comment by lenny-intel** [comment]
@andresrinivasan , I finally got back to this. Also getting this error from Support Scheduler
```
level=ERROR ts=2019-11-08T23:36:34.3436466Z app=edgex-support-scheduler source=init.go:49 msg="Failed to load schedules and events ERR unknown command `RANGE`, with args beginning with: `interval`, `0`, `-1`, 
```

Add this from Support Command.
```
level=WARN ts=2019-11-08T23:37:03.5325415Z app=edgex-core-command source=database.go:125 msg="couldn't create database client: no reachable servers"
```

**Comment by andresrinivasan** [comment]
Thanks. I'll be able to start looking at this next week.

**Comment by lenny-intel** [comment]
@andresrinivasan , this bug may be the root of this issue.
https://github.com/edgexfoundry/edgex-go/issues/2064

**Comment by lenny-intel** [comment]
edgexfoundry/edgex-go#2064 fixed this issue.
