### ISSUE TITLE
Remove config-seed service from nexus docker-compose files

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/developer-scripts#189]
Coordinate with changes made in https://github.com/edgexfoundry/edgex-go/issues/2236.

Dependent upon completion of https://github.com/edgexfoundry/go-mod-bootstrap/issues/14.

**Comment by lenny-intel** [comment]
Also have to apply additional environment overrides for removal of Docker profiles.

**Comment by lenny-intel** [comment]
PR for this ADR edgexfoundry/edgex-docs#115 has consensus and in process of TSC approval, so moving forward with a PR for this which covers all the config-seed removal and env overrides portions for the ADR.
