### ISSUE TITLE
Exposed ports of microservices need to be disabled in docker compose file	

### ISSUE THREAD

**Issue by tingyuz** [edgexfoundry/developer-scripts#190]
Currently microservices in EdgeX expose ports ( e.g, 48080 etc) without protection. With proxy in place for Fuji release, these ports need to be disabled and all the access to microservices need to go through proxy.

**Comment by tingyuz** [comment]
Attached the response from Cloud to show that the QA group already implemented methods to access EdgeX resources through KONG proxy. As the discussion thread mentioned above, we prefer to cover this in the deployment guide other than removing the port exposed through docker-compose file. 
---------------------------------------------------------------------
From: Cloud Tsai <cloud@iotechsys.com>
Sent: Wednesday, February 26, 2020 9:01 AM
To: Jim White
Cc: Zeng, Tingyu; Robin Chatterjee; Andrew Foster; Cherry Wang
Subject: Re: issue #190 of developer-scripts - blocking exposed microservice ports
 
[EXTERNAL EMAIL] 

Hi all,

Currently, the blackbox test with security enabled is testing services via Kong.  That's the improvement mentioned by Tingyu.
However, I don't think we need to test access is actually denied when trying to access the APIs outside of security, because it is basically testing the firewall not provided by us.  Unless we include a firewall into our scope.
The easiest way to disable every access from outside to the individual micro service is to remove the port mapping in the docker-compose file.  Isolating the services in the docker network can achieve this objective.  Also, I still don't think we should make sure the access of each service from outside is denied, because it is testing the docker network.

For example, remove the port section in the service and only keep the port mapping for Kong.

command:

image: 
nexus3.edgexfoundry.org:10004/docker-core-command-go:master

ports:

- "48082:48082"

container_name: 
edgex-core-command

hostname: 
edgex-core-command

networks:

- edgex-network

volumes:

- /tmp/edgex/secrets/ca:/tmp/edgex/secrets/ca:ro,z

- /tmp/edgex/secrets/edgex-core-command:/tmp/edgex/secrets/edgex-core-command:ro,z

depends_on:

**Comment by tingyuz** [comment]
As discussed during the security WG meeting on March 25th, this will be addressed as part of #236. Leaving this open for reference.

**Comment by tingyuz** [comment]
Close this as the related issue of #236 has been closed.

**Comment by bnevis-i** [comment]
Reopening; pr never merged due to upstream drift.
