### ISSUE TITLE
Add ARM64 redis docker compose file for nexus release

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/developer-scripts#207]
Need to create docker-compose-nexus-redis-no-secty-arm64.yml for [edgexfoundry/blackbox-testing#344](https://github.com/edgexfoundry/blackbox-testing/issues/344)

**Comment by andresrinivasan** [comment]
The only difference between an AMD64 and an ARM64 Docker Compose file is which Redis image you use. Can we get creative with environment variables or `.env` files?

**Comment by cloudxxx8** [comment]
@andresrinivasan there is a plan to merge all the docker-compose file into one with variables to deal with, x86, ARM, mongo, and redis.  However, we need this one for now for the blackbox test.
