### ISSUE TITLE
about docker-compose-nexus-arm64.yml

### ISSUE THREAD

**Issue by fovVdk** [edgexfoundry/developer-scripts#209]
I try to use this build, But docker logs show errors about edgex-support-rulesengine，The specific content is as follows：
 A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (assembler_aarch64.hpp:1156), pid=7, tid=0x0000007f9664aa78
#  guarantee(Rs != Rn && Rs != Rt) failed: unpredictable instruction
#
# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-aarch64 compressed oops)
# Derivative: IcedTea 3.12.0
# Distribution: Custom build (Mon May  6 07:45:11 UTC 2019)
# Core dump written. Default location: /edgex/edgex-support-rulesengine/core or core.7
#
# An error report file with more information is saved as:
# /edgex/edgex-support-rulesengine/hs_err_pid7.log
#
# Compiler replay data is saved as:
# /edgex/edgex-support-rulesengine/replay_pid7.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   https://icedtea.classpath.org/bugzilla

**Comment by bnevis-i** [comment]
We have a nightly regression and don't observe this failure.  Do you have more details about the underlying platform?

**Comment by fovVdk** [comment]
My runtime environment：Linux Kernel4.9 ，Ubuntu18.04
