### ISSUE TITLE
about  the use of edgex-go under arm64

### ISSUE THREAD

**Issue by fovVdk** [edgexfoundry/developer-scripts#210]
because I  need  to  use under arm64, so  I need to read codes of edgex-go under arm64, but I can only find docker-compose about arm64 in nexus，so  can you give me url  about codes

**Comment by bnevis-i** [comment]
@fovVdk 

The main respository for EdgeX source code is https://github.com/edgexfoundry/edgex-go.

Does this answer your question?

**Comment by bnevis-i** [comment]
Closed due to age.
