### ISSUE TITLE
Security services health checks are being executed for no-security docker-compose scenarios

### ISSUE THREAD

**Issue by fovVdk** [edgexfoundry/developer-scripts#213]
I have completed the execution according to docker-compose, and the error message is as follows:
[ERR] agent: Check "service:security-secretstore-setup" failed to invoke: fork/exec /consul/scripts/security-secretstore-setup-checker.sh: no such file or directory
    2020/01/15 08:32:11 [ERR] agent: Check "service:kong-migrations" failed to invoke: fork/exec /consul/scripts/kong-migrations-checker.sh: no such file or directory
    2020/01/15 08:32:11 [ERR] agent: Check "service:kong-db" failed to invoke: fork/exec /consul/scripts/kong-db-checker.sh: no such file or directory
    2020/01/15 08:32:11 [ERR] agent: Check "service:security-secrets-setup" failed to invoke: fork/exec /consul/scripts/security-secrets-setup-checker.sh: no such file or directory

**Comment by bnevis-i** [comment]
@fovVdk Are these error fatal to any component?

This are consul health checks that are being injected into the consul configuration by the following folder:
`https://github.com/edgexfoundry/docker-edgex-volume/tree/master/config`

These errors can be ignored for the non-security version of EdgeX unless it is causing other problems.
