### ISSUE TITLE
Docker Compose: Consul Image Difference (Secure vs Non-Secure)

### ISSUE THREAD

**Issue by beaufrusetta** [edgexfoundry/developer-scripts#220]
Why is it, in the Fuji release, that the non-secure version of the docker-compose file uses `image: consul:1.3.1` and in the secure version it uses `image: edgexfoundry/docker-edgex-consul:1.1.0`?

I'm working on something right now using the docker-compose file for Fuji, and its throwing a lot of random errors in the error log because consul can't seem to find the bash scripts that it's trying to run located under `/consul/scripts`. 

I'm also a n00b...and a manager...sooooo it's likely I've missed something here. :-)

**Comment by lenny-intel** [comment]
edgexfoundry/docker-edgex-consul:1.1.0 has all the sequencing support stuff for bring all the services up in proper order in secure mode.

**Comment by beaufrusetta** [comment]
> edgexfoundry/docker-edgex-consul:1.1.0 has all the sequencing support stuff for bring all the services up in proper order in secure mode.

And that container image also contains scripts that are included at build time that the other consul image does not...however, both look for the same scripts...one just has more failures and writes to the log a lot more.

**Comment by bnevis-i** [comment]
This is a problem.  The scripts that are currently injected by docker-edgex-volume that should be moved to the custom consul container and only injected into the appropriate location at runtime based on whether or not security is enabled.

The constant retrying for files that do not exist may also consume excessive CPU as well.
