### ISSUE TITLE
Implement network micro-segmentation in docker-compose

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/developer-scripts#238]
Sub-story of https://github.com/edgexfoundry/edgex-go/issues/1950

Network micro-segmentation is a defense-in-depth strategy against rogue microservices by constraining the available communication paths.

For this issue, reverse engineer EdgeX microservice communication patterns and codify these patterns into docker networks.  For example:

- https://docs.google.com/presentation/d/1t7OqrfEkBn4OYQO5PTcx7P1fyo0Q22_bWMcaRT045oc/edit#slide=id.g82f672199f_0_2
- portainer, secrets-setup isn't on any network
- kong's primary network is "hostnet" (see https://docs.docker.com/compose/compose-file/#network-configuration-reference#network-configuration-reference)
- kong and kong-db should communicate on a dedicated network
- mongo, redis, consul, vault, and vault-worker live on persistence-net
- remaining services are double-homed on edgex-network (primary) and persistence-net (secondary)

**Comment by lenny-intel** [comment]
@bnevis-i , per our latest discussion, is this issue still valid/needed?

**Comment by bnevis-i** [comment]
Based on the connectivity diagram (linked in description) to explore this idea further, the number of strongly connected components (like kong and kong-db) is very low.  For example, since almost everyone talks to Vault and Consul, it doesn't on further analysis seem to make sense to separate them into their own network.   Most of the other microservices are many-many.  Microservice authentication provides a more tangible security benefit than micro-segmentation.  Closing issue.
