### ISSUE TITLE
Wrong Consul Image in Nightly-Build + Redis + No Security

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/developer-scripts#242]
In the nightly build image using Redis without security, it appears that the wrong image of Consul is being referenced. It should be the wrapped image created by us, but we're pointing to the vanilla Consul 1.3.1 image.
https://github.com/edgexfoundry/developer-scripts/blob/ab0e3388015944cb40999e80ecd7c00b33657060/releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml#L58

This causes numerous errors due to security-related scripts that aren't present in the vanilla Consul image.
```
edgex-core-consul    |     2020/04/07 15:23:04 [ERR] agent: Check "service:security-proxy-setup" failed to invoke: fork/exec /consul/scripts/security-proxy-setup-checker.sh: no such file or directory
edgex-core-consul    |     2020/04/07 15:23:04 [WARN] agent: Check "service:kong" HTTP request failed: Get http://kong:8001/status: dial tcp 23.217.138.110:8001: connect: connection refused
edgex-core-consul    |     2020/04/07 15:23:04 [ERR] agent: Check "service:kong-db" failed to invoke: fork/exec /consul/scripts/kong-db-checker.sh: no such file or directory
edgex-core-consul    |     2020/04/07 15:23:04 [ERR] agent: Check "service:kong-migrations" failed to invoke: fork/exec /consul/scripts/kong-migrations-checker.sh: no such file or directory
edgex-core-consul    |     2020/04/07 15:23:04 [ERR] agent: Check "service:security-secrets-setup" failed to invoke: fork/exec /consul/scripts/security-secrets-setup-checker.sh: no such file or directory
edgex-core-consul    |     2020/04/07 15:23:04 [ERR] agent: Check "service:security-secretstore-setup" failed to invoke: fork/exec /consul/scripts/security-secretstore-setup-checker.sh: no such file or directory
edgex-core-consul    |     2020/04/07 15:23:05 [ERR] agent: Check "service:security-proxy-setup" failed to invoke: fork/exec /consul/scripts/security-proxy-setup-checker.sh: no such file or directory
```
It might also be expected that none of the above operations should be triggered in a scenario where security is disabled. But in any case if I replace the line referenced above with a pointer to our nightly `docker-edgex-consul` image the errors go away.

`image: nexus3.edgexfoundry.org:10004/docker-edgex-consul:master`

@bnevis-i @lenny-intel Thoughts?

**Comment by bnevis-i** [comment]
Duplicate of #220

**Comment by bnevis-i** [comment]
@tsconn23 A PR that addresses the issue is being formulated...  1.3.1 is out of date anyway.
