### ISSUE TITLE
no right to pull image from nexu3.edgexfoundry.org:1003

### ISSUE THREAD

**Issue by KantKatze** [edgexfoundry/developer-scripts#26]
wen I run "docker-compose up -d config-seed" by using compose-dev.yml, the following output is 

**Pulling config-seed (nexus3.edgexfoundry.org:10003/docker-core-config-seed:latest)...
ERROR: Get https://nexus3.edgexfoundry.org:10003/v2/docker-core-config-seed/manifests/latest: no basic auth credentials**

**Comment by trcox** [comment]
@KantKatze The Linux Foundation Nexus hosting for Docker images does not allow unauthenticated access. You can use the credentials docker:docker for read access to the nightly builds.

https://github.com/edgexfoundry/developer-scripts/blob/4bf1a235b8397aa19d5ade5ce54d447952ed8f42/docker-compose-dev.yml#L3

**Comment by trcox** [comment]
Additionally, for tracking purposes, #24 is the feature request to watch for the image builds to go out to Docker Hub nightly on an `edge` tag rather than requiring the use of the nexus3 Docker Registry referenced by the docker-compose-dev.yml.
