### ISSUE TITLE
Remove port 8400 for Consul in docker compose files

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/developer-scripts#296]
Doesn't appear port 8400 is required by Consul (https://www.consul.io/docs/install/ports) and it causes problems in health checks for things like AWS.

**Comment by lenny-intel** [comment]
And now it is so simple... One line change, not 8... ;-)

**Comment by lenny-intel** [comment]
Per the table at this link, 8400 isn't a valid Consul port.
https://www.consul.io/docs/install/ports
