### ISSUE TITLE
Unable register with Registry because of the failure of core-consul

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/developer-scripts#301]
The log of core-consul:
```
Installing redis health checks
cp: can't create '/consul/scripts/consul-svc-healthy.sh': Read-only file system
cp: can't create '/consul/scripts/health': Read-only file system
cp: can't create '/consul/scripts/kong-db-checker.sh': Read-only file system
cp: can't create '/consul/scripts/kong-migrations-checker.sh': Read-only file system
cp: can't create '/consul/scripts/security-secrets-setup-checker.sh': Read-only file system
cp: can't create '/consul/scripts/security-secretstore-setup-checker.sh': Read-only file system
```

**Comment by cloudxxx8** [comment]
This issue blocks all the edgex services start up normally

**Comment by bnevis-i** [comment]
Need more information about the failure, specifically: which docker-compose is failing?

Specifically, the add-security docker-compose files explicitly mount a writable volume there (abbreviated) specifically for this reason?

Please try a "make build" to recompose the compose file if it differs from what is in version control.

```
volumes:
  consul-scripts:

services:
  consul:
    volumes:
      - consul-scripts:/consul/scripts:z
```

**Comment by jpwhitemn** [comment]
Blocking all blackbox tests?  Ginny to confirm/with Cloud

**Comment by jinlinGuan** [comment]
The failed blackbox tests on Jenkins use nightly-build no security compose files (docker-compose-nexus-no-secty.yml and docker-compose-nexus-no-secty-arm64.yml).  I recomposed the compose files, but there was no difference.

For the blackbox-testing security-enabled tests, only app-service-configurable testcases fail, so I'm investigating it.

**Comment by bnevis-i** [comment]
The failure has to do with this line

`if [ "$Secure_Check" = 'true' ]; then`

which is inexplicably executing when Secure_Check = false

**Comment by jinlinGuan** [comment]
> Specifically, the add-security docker-compose files explicitly mounts a writable volume there (abbreviated) just for this reason:

I added the volume, and the consul and all edgex services started up normally.

**Comment by bnevis-i** [comment]
> I added the volume, and the consul and all edgex services started up normally.

Yep, that's the fix.  Do you want to put together the PR or should I?

**Comment by bnevis-i** [comment]
> I added the volume, and the consul and all edgex services started up normally.

There's something off about the cp statement in the consul container as well.  Let me work on the PR.

**Comment by bnevis-i** [comment]
PR submitted. Please validate.  Consul container is OK after all -- it was intended that the health checking utilities (/consul/scripts/health) be available in all configurations just in case so that containers can check other service dependencies.
