### ISSUE TITLE
Add Generation of TAF and Blackbox tests specific compose files

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/developer-scripts#305]
Currently TAF and Black box tests pull one of the standard generated compose files from the nightly build compose files and augment them for additional services to run. This causes maintenance issues with those additional compose files becoming out of date and is more complex for the community to run the tests.

With the new multi-file compose and generation of all in one compose files, it is cleaner to add generation of TAF & Blackbox Tests specific compose files that don't require augmentations. Note that these new generated compose files will need ARM64 and  no-secty variations. Also, these test specific generated compose file should be put under new sub-folder so not to clutter the standard generated compose files.

The current additional TAF compose files are here:
https://github.com/edgexfoundry/edgex-taf/blob/master/TAF/utils/scripts/docker/docker-compose-device-service.yaml
https://github.com/edgexfoundry/edgex-taf/blob/master/TAF/utils/scripts/docker/docker-compose-end-to-end.yaml
Also see scripts in this same folder to see how these compose files are used and documentation here:
https://github.com/edgexfoundry/edgex-taf/blob/master/docs/edgex-taf.md

The current additional Blackbox tests compose file is here:
https://github.com/edgexfoundry/blackbox-testing/blob/master/docker-compose-test-tools.yml
Also see scripts in this same folder/sub-folders to see how these compose files are used.

**Comment by lenny-intel** [comment]
@cloudxxx8 , any additional information I missed?

**Comment by cloudxxx8** [comment]
@cherrycl please help confirm the information in this issue.

**Comment by cherrycl** [comment]
@lenny-intel @cloudxxx8 The comment looks good. I didn't find any missed information.

**Comment by cherrycl** [comment]
Just found, the edgex-taf.rst is replaced by [edgex-taf.md](https://github.com/edgexfoundry/edgex-taf/blob/master/docs/edgex-taf.md).

**Comment by lenny-intel** [comment]
> Just found, the edgex-taf.rst is replaced by [edgex-taf.md](https://github.com/edgexfoundry/edgex-taf/blob/master/docs/edgex-taf.md).

Adjusted for doc format change. THX!
