### ISSUE TITLE
README.md of developer-scripts does not reflect current reality

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/developer-scripts#306]
The https://github.com/edgexfoundry/developer-scripts/blob/master/README.md of the developer-scripts repository does not accurately reflect how the developer-scripts are currently being used.  The root directory of this repository contains a number of scripts that may no longer be relevant.

**Comment by lenny-intel** [comment]
closing this issue as the repo has been replaced by edgex-compose . An issue for proper README has be added for that repo.
