### ISSUE TITLE
manifest for vault:1.5 not found

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/developer-scripts#313]
Blackbox-testing security-enabled tests fail because there is no tag 1.5 for vault.
nightly-build compose files:
https://github.com/edgexfoundry/developer-scripts/blob/c82f71f47101e426fb60f5978646a98da66e2067/releases/nightly-build/compose-files/docker-compose-nexus.yml#L535
https://github.com/edgexfoundry/developer-scripts/blob/c82f71f47101e426fb60f5978646a98da66e2067/releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml#L535

Related: https://github.com/edgexfoundry/developer-scripts/pull/312

**Comment by cloudxxx8** [comment]
add @hutchic for awareness
