### ISSUE TITLE
Proxy setup reports error setting up ACL when using Kong 2.1

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/developer-scripts#315]
security-proxy-setup is now reporting the following errors since we switch to Kong 2.1 . 
```
level=ERROR ts=2020-09-08T17:45:40.058584301Z app=edgex-security-proxy-setup source=service.go:448 msg="failed to set up acl with errorcode 400"
level=ERROR ts=2020-09-08T17:45:40.058803009Z app=edgex-security-proxy-setup source=init.go:62 msg="failed to set up acl with errorcode 400"
```

I locally rolled back to previous version, `Kong 2.0.1`, and verified this was not occurring.

**Comment by lenny-intel** [comment]
Note that the API gateway seems to be working fine with these errors. I was able to acquire a token abd successful to GET on to Core Data Ping API via the API Gateway.

**Comment by hutchic** [comment]
@lenny-intel what's the docker-compose container name in developer-scripts where this error can be seen?
