### ISSUE TITLE
Make kuiper rules engine root file system read-only

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/developer-scripts#320]
An [issue](https://github.com/emqx/kuiper/issues/381) that has been blocking makign the kuiper container read-only has been resolved.

This will require a version bump and adding additional volumes to the docker-compose.

**Comment by lenny-intel** [comment]
Per Rocky at App Service WG, that fix will be available in the 1.0.0 release this month. 
Note that they have made changes to the Env Var names so those update will need to happen also for the change to use 1.0.0 to work properly

**Comment by beaufrusetta** [comment]
> Per Rocky at App Service WG, that fix will be available in the 1.0.0 release this month.
> Note that they have made changes to the Env Var names so those update will need to happen also for the change to use 1.0.0 to work properly

@lenny-intel what env variables need to be updated? What do they need to be updated to? Or has that already happened?

**Comment by lenny-intel** [comment]
@beaufrusetta , Those `env variable` updates were already made when we updated to using 1.0.0 for Hanoi.
