### ISSUE TITLE
Inconsistent Service_Host and hostname in security-bootstrap-database service

### ISSUE THREAD

**Issue by hahattan** [edgexfoundry/developer-scripts#346]
https://github.com/edgexfoundry/developer-scripts/blob/56740441ccbc69cac7afcbb52f449620d081dc51/releases/nightly-build/compose-files/docker-compose-nexus.yml#L493-L494

Just came across these configuration and wondering will it cause any potential error if `Service_Host` is inconsistent with container's `hostname` (they are identical for all other services)

**Comment by lenny-intel** [comment]
Good catch! It doesn't cause issues since this service doesn't have any REST API. It should be fix for consistency purposes.

**Comment by lenny-intel** [comment]
Fixing this in the Hanoi release PR (https://github.com/edgexfoundry/developer-scripts/pull/343)

**Comment by hahattan** [comment]
@lenny-intel just a reminder that `SERVICE_HOST` is still wrong in Hanoi compose file:
https://github.com/edgexfoundry/developer-scripts/blob/949ebf1d6ff5c79a79265c79cc8107f8895f21f2/releases/hanoi/compose-files/docker-compose-hanoi.yml#L493-L494

They're the same in nightly-build though:
https://github.com/edgexfoundry/developer-scripts/blob/949ebf1d6ff5c79a79265c79cc8107f8895f21f2/releases/nightly-build/compose-files/docker-compose-nexus.yml#L493-L494

I'm good with it if they're not causing any issue (opening this PR just for clarification whether they should be the same)

**Comment by cloudxxx8** [comment]
We should make it conisistent.

**Comment by lenny-intel** [comment]
> just a reminder that `SERVICE_HOST` is still wrong in Hanoi compose file:

@hahattan , @cloudxxx8 ,

Yes, I fixed it in the source compose file but forgot to run `make build`. I did run `make build` for nightly, so it is fixed there. 

Since it is just inconsistent naming and no side effects, it can be addressed for Hanoi if we have a point release. Thoughts?
