### ISSUE TITLE
Make docker container images run as non-root users

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/developer-scripts#371]
# 🚀 Feature Request

### Relevant Package
Affects the Dockerfile for every EdgeX service and may initially require workarounds or code changes for containers that do not support running as non-root.

### Description
Almost all of the EdgeX Docker containers run at root privilege.  This is a scored item in the Docker CIS benchmark.  Root user containers are dangerous because in the default docker installation (with user namespace remapping disabled), the root user in a container is the same root UID as a host.  If a container were able to obtain read/write access to the host file system, such a container may be able to tamper with root-only files.  Similarly, system calls also maintain root-level privilege.

### Describe the solution you'd like
Each EdgeX service should be assigned a unique non-root user ID and the respective service should run under the identity of that user ID.  Note that it is not necessary that the user ID be mapped to a passwd entry on the host.  However, if that is desired, systemd-based installations provide functionality, [systemd-sysusers](https://www.freedesktop.org/software/systemd/man/sysusers.d.html), to pre-create service accounts with fixed user IDs at system startup.  (Only fixed UIDs make sense for Docker.)

**Comment by beaufrusetta** [comment]
This issue should be closed? The changes made with this [PR ](https://github.com/edgexfoundry/edgex-go/pull/3003)to accommodate this request do not require any developer-scripts changes.

@lenny-intel @bnevis-i @jim-wang-intel

**Comment by lenny-intel** [comment]
address by #374

**Comment by hahattan** [comment]
@lenny-intel @beaufrusetta 
I noticed that some services are still running as root user:
`consul`, `redis`, `secretstore-setup`, `security-bootstrapper`, `vault`, `kong`, `kong-db`, `kuiper`
are we planning to make them run as non-root user eventually or the root privilege is necessary for them ?

thanks

**Comment by lenny-intel** [comment]
> I noticed that some services are still running as root user:

@hahattan , `secretstore-setup` and `security-bootstrapper` will always run as root. `kuiper` will run as non-root in the next release coming this month. `consul`, `redis`, `vault`, `kong-db`  run as non-root. What you are seeing is the entry point scripts, not the actual process for those services which run as their own user.
