### ISSUE TITLE
[app-service] make gen dev doesn't generate the -dev version of docker image names for App-Services

### ISSUE THREAD

**Issue by jim-wang-intel** [edgexfoundry/developer-scripts#380]
Currently, the command `make gen dev` works well for docker image names from `edgex-go` services with `-dev` appendix. However, this is not generated correctly for those from `app-service-configureable`.  
asc-related services should also have `-dev` as appendix when `make gen app-dev` is run.

- use flag `dev` for dev version of edgex-go's services
- use flag `app-dev` for dev version of app-service-configurable's service

**Comment by lenny-intel** [comment]
Not a bug. They are separate builds, so can't assume `dev` is for anything but the edgex-go service. Sounds like this really is an enhancement request for additional app-dev option.

**Comment by jim-wang-intel** [comment]
> Not a bug. They are separate builds, so can't assume `dev` is for anything but the edgex-go service. Sounds like this really is an enhancement request for additional app-dev option.

Ok, thanks for elaboration! It will be much easier if can produce `-dev` for app-services as well because I'm testing the whole asc stacks in `security-bootstrapper`  as well.
