### ISSUE TITLE
Rename blackbox-tests to functional-tests in a/compose-builder/add-taf-app-services.yml

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/developer-scripts#382]
We are removing the term "blackbox-tests" from the test script, so we need to rename this configuration profile name.
/compose-builder/add-taf-app-services.yml

**Comment by cloudxxx8** [comment]
this issue is blocked by https://github.com/edgexfoundry/app-service-configurable/issues/177

**Comment by lenny-intel** [comment]
Unable to complete this until PR #372 is able to merge.
