### ISSUE TITLE
Improved formatting of docker-compose-hanoi-no-secty-arm64.yml

### ISSUE THREAD

**Issue by punidramesh** [edgexfoundry/developer-scripts#400]
Till the Geneva release, the docker-compose files had a proper structure in definitions

An example would be : 

version: 
environment variables
volumes:
services:
  consul:
  redis:
system:
  notifications:
  metadata:
  data:
  command:
  scheduler:
  app-service-rules:
  rulesengine:

  device-virtual:
  device-rest:
  device-random:
  device-mqtt:
  device-modbus:
  device-snmp:
networks:

But in the Hanoi release, this structure is not followed and makes the process of development tedious.

**Comment by punidramesh** [comment]
I would like to contribute to this issue

**Comment by lenny-intel** [comment]
@punidramesh , the compose files are now generated from multiple compose files using the `docker-compose config` command. This command outputs the all the services and their properties/setting alphabetically. There is noting improper about this structure.
See the `compose-builder` README here: https://github.com/edgexfoundry/developer-scripts/blob/master/compose-builder/README.md

**Comment by punidramesh** [comment]
Oh I see. I shall be closing this issue now.
