### ISSUE TITLE
California release does not work with device-modbus:0.6.0

### ISSUE THREAD

**Issue by jeremylin06** [edgexfoundry/developer-scripts#63]
Trying to integrate California release with device-modbus:0.6.0 (using docker-compose-california-0.6.0.yml) . It failed. No connection made to modbus simulator. If using docker-compmose-nexus.yml (commenting out duplicated port mapping in service config-seed), the modbus integration succeeds. It looks like the images in docker hub registry (hub.docker.com/edgexfoundry) are different from images in nexus (nexus3.edgexfoundry.org:10004).

**Comment by jpwhitemn** [comment]
Is this just an image/container issue or a bug in Modbus?

**Comment by jeremylin06** [comment]
It should be image problem (when pulled from docker hub)
