### ISSUE TITLE
Separate Mongo/Mongo-seed into two containers (Docker)

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/developer-scripts#65]
In the same way that we split the consul and core-config-seed-go Docker containers for the California release, we need to do the same for Mongo. Right now, the Mongo platform is coupled in deployment with a population script in mongo-seed. These should run separately and the mongo image should come directly from mongo, rather than being wrapped in an "edgex" image.

**Comment by lenny-intel** [comment]
So if I understand this correctly, you want a new micro-service (aka mongo-seed) that does the work of the init_mongo.js?

**Comment by tsconn23** [comment]
@lenny-intel Gosh, I had forgotten all about this. There was some issue we had during the California release that lead me to create this, but we're trucking right along now so I don't think this is relevant anymore.

**Comment by jpwhitemn** [comment]
being worked for Fuji but as separate repo.   Pulling this issue from here.
