### ISSUE TITLE
mapping values are not allowed here

### ISSUE THREAD

**Issue by Danmo82** [edgexfoundry/developer-scripts#72]
I am getting this error from docker on my ubuntu when running the command

`docker-compose pull`

**yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 387, column 24**

Ubuntu version: 18.04 server
docker Version:      17.06.2-
docker-compose version 1.16.1

**Comment by TapioT** [comment]
I am having the same issue on CentOS Linux release 7.5.1804 (Core)

**Comment by jpwhitemn** [comment]
Closing per Toby's fix above
