### ISSUE TITLE
docker-compose.yml : error pulling consul

### ISSUE THREAD

**Issue by ClementChotard** [edgexfoundry/developer-scripts#76]
Hi,
Docke-compose is unable to pull the consul micro-service. I tried several docker compose files but it remains the same.
Here is the error:
```
ERROR: for consul no matching manifest for unknown in the manifest entries
ERROR: no matching manifest for unknown in the manifest list entries
```

**Comment by jpwhitemn** [comment]
Having no issues pulling Consul 1.1.0 or 1.3.1 which is represented in most of the compose files.
