### ISSUE TITLE
Devops Installer for EdgeXfoundry?

### ISSUE THREAD

**Issue by noelmcloughlin** [edgexfoundry/developer-scripts#77]
When I attended the Edinburgh summit last month I drew this sketch for an automatic installer for EdgeXfoundry Developers. I remembered this today. Just wondering if there is interested in such a DevOps installer for edgexfoundary Developers.  

Background
It would be hosted at https://github.com/saltstack-formulas/ and following a design pattern I used for  [OpenSDS (needs more work, testing)](https://github.com/saltstack-formulas/opensds-formula) and [OpenStack-Devstack](https://github.com/saltstack-formulas/devstack-formula).

Generic Architecture Diagram
If someone wanted to do the same in Ansible or some other IT automation tool, the architecture would be similar - only the box labels change.

Related PR:
In anticipation of doing this I raised a [PR on MongoDB](https://github.com/saltstack-formulas/mongodb-formula/pull/51) which stuck at the moment but once that gets merged then I could start an implementation. Everything else (eclipse, docker, etc) is covered by saltstack-formulas. 

![solutiondesignedgexfoundry](https://user-images.githubusercontent.com/13322818/48557367-6fbf6c80-e8de-11e8-908c-18c285af6193.png)

**Comment by tsconn23** [comment]
You're certainly welcome to explore a solution like this. I don't know that we'd take something like this on as an official part of the project though. But we are always looking for use cases that could serve as a basis for blog posts, online demos or tech talks and this would be applicable.

**Comment by noelmcloughlin** [comment]
Thanks. I agree it should not be part of official project since its a distraction.  I'll look into doing the work soon (once MongoDB is merged).  Basically the repo will have a `site.j2` file in which site and release specific details can be applied, but in reality only the **release** (i.e. Calfornia / latest) might change. Therefore the end-user has little to do.

Technically the IT automation tool (saltstack in my case) would curl down the `docker-compose.yml`, import as Jinja2 (python) dictionary and iterate over the services which comprise EdgeXfoundary.

**Comment by jpwhitemn** [comment]
@noelmcloughlin - projects and work in this area have been featured on our blog and we can also provide space on the wiki for guided how-to-documents provided by contributors.  As Trevor indicated, we want to be careful not to incorporate directly into the project code base, but we can help to facilitate where there is a good use case and success that helps those who adopt EdgeX.  A blog post or Wiki page allows you to also link to other web spaces (personal or corporate) where you might provide more detail or code examples, etc.

**Comment by noelmcloughlin** [comment]
Thank you both for the responses. I'm encouraged to look into this idea further. I agree to implement something which integrates with EdgeX developer scripts API (which I see being docker-compose.yml file) without forcing EdgeX to maintain a project relationship.

One value-add would be capability to deploy EdgeXfoundry services in distributed fashion - i.e. consume docker-compose.yml artifact but don't use `docker compose` command. Distributed deployment of "things" is a standard feature of Salt, Ansible, anyway.

I'll close this issue in a few days and reopen when something is available.

**Comment by noelmcloughlin** [comment]
Closing for now. The building blocks are all ready at saltstack-formulas so just needs an impl.
