### ISSUE TITLE
Update Consul version to v1.3.1

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/developer-scripts#85]
Per Edinburgh F2F, update Consul to use version 1.3.1. Changes will be made to the following:

- docker-compose.yml
- docker-compose-nexus.yml

These compose files are not specific to a release and are used for pulling images based on `master` WIP

**Comment by anonymouse64** [comment]
The edinburgh docker-compose file still has 1.1 referenced in it:

https://github.com/edgexfoundry/developer-scripts/blob/cc0a6c6313e3143a44400718de42845a41f405f2/compose-files/docker-compose-edinburgh-1.0.0.yml#L40

as does the redis version:

https://github.com/edgexfoundry/developer-scripts/blob/cc0a6c6313e3143a44400718de42845a41f405f2/compose-files/docker-compose-redis-edinburgh-1.0.0.yml#L40
