### ISSUE TITLE
Update Raspberry PI Howto doc

### ISSUE THREAD

**Issue by noelmcloughlin** [edgexfoundry/developer-scripts#94]
Apologies for logging this issue here - I was unsure of correct forum.

Could you update Pi [HOWTO](https://wiki.edgexfoundry.org/display/FA/Runnning+on+a+RaspberryPi#RunnningonaRaspberryPi-InstalltheOS) for MacOS.  The `dd` device is typically `of=/dev/disk2`.
```
bash-3.2# ls
Bamarni-desktop-full64bit-pi3bplus-V2.img
bash-3.2# diskutil list
/dev/disk0 (internal):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                         251.0 GB   disk0
   1:                        EFI EFI                     314.6 MB   disk0s1
   2:                 Apple_APFS Container disk1         250.7 GB   disk0s2

/dev/disk1 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +250.7 GB   disk1
                                 Physical Store disk0s2
   1:                APFS Volume Macintosh HD            217.6 GB   disk1s1
   2:                APFS Volume Preboot                 22.5 MB    disk1s2
   3:                APFS Volume Recovery                515.0 MB   disk1s3
   4:                APFS Volume VM                      2.1 GB     disk1s4

/dev/disk2 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *15.9 GB    disk2
   1:             Windows_FAT_16 RECOVERY                1.5 GB     disk2s1
   2:                      Linux                         33.6 MB    disk2s5
   3:                 DOS_FAT_32 BOOT                    72.4 MB    disk2s6
   4:                      Linux                         14.4 GB    disk2s7

bash-3.2# 
bash-3.2# diskutil unmountdisk /dev/disk2
Unmount of all volumes on disk2 was successful
bash-3.2# dd if=Bamarni-desktop-full64bit-pi3bplus-V2.img of=/dev/disk2 bs=2m
1476+1 records in
1476+1 records out
3096563712 bytes transferred in 153.621726 secs (20157069 bytes/sec)
```

**Comment by noelmcloughlin** [comment]
Never mind - this is already covered. Cool.

> Note that you will need to replace the part in bold with the path to your own microSD card, and that it should point to the device and not a partition on the device.

**Comment by noelmcloughlin** [comment]
Maybe I should note three deviations to article:

1. Glide install failure (requires go). Workaround was to pass *PATH=* to sudo
 `curl https://glide.sh/get |sudo PATH=/usr/local/go/bin:$PATH GOPATH=/usr/local/go sh`

2. Glide [No Dist error](https://github.com/Masterminds/glide/issues/1028) has workaround-
`wget https://github.com/Masterminds/glide/releases/download/v0.13.1/glide-v0.13.1-linux-arm64.tar.gz && sudo tar -zxvf glide-v0.13.1-linux-arm64.tar.gz && sudo mv ./linux-arm64/glide /usr/local/bin/`

3. `make build` failed. Solution was `sudo apt-get install pkg-config -y`

**Comment by noelmcloughlin** [comment]
Otherwise procedure worked nicely!!

**Comment by anonymouse64** [comment]
@noelmcloughlin we have updated the Running on Raspberry Pi page and I think all of your points have been addressed and I think this issue can be closed

**Comment by noelmcloughlin** [comment]
Thanks @anonymouse64 Looks good.
